; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
#define MyAppName "IL-2 Great Battles SP Campaign Tracker Multi Language"
#define MyAppExeName "IL2_CampaignTracker_v2.1_ML.exe"
#define MyAppVersion "2.1"
#define MyAppPublisher "Arrow_1"

[Setup]
AppId={{1c17a2fd-8f7a-424f-b1b6-702505698a52}}  ; <-- change to a real GUID and keep it stable
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
PrivilegesRequired=admin
DefaultDirName={localappdata}\{#MyAppName}
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes

OutputBaseFilename=IL2_CampaignTracker_Setup_v{#MyAppVersion}
Compression=lzma
SolidCompression=yes

UsePreviousAppDir=yes

UninstallDisplayName=IL-2 Great Battles SP Campaign Tracker Uninstaller
UninstallDisplayIcon={app}\IL2_CampaignTracker_v2.1_ML.exe

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "german"; MessagesFile: "compiler:Languages\German.isl"
Name: "french"; MessagesFile: "compiler:Languages\French.isl"
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"
Name: "polish"; MessagesFile: "compiler:Languages\Polish.isl"
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"
Name: "chinesesimplified"; MessagesFile: "compiler:Languages\ChineseSimplified.isl"

[CustomMessages]
; ============================================================================
; ENGLISH (default)
; ============================================================================
english.SelectIL2Folder=Please select an existing IL-2 Great Battles installation folder.
english.InvalidIL2Folder=The selected folder does not appear to be a valid IL-2 Great Battles installation.%nPlease select the correct game installation directory.
english.RemoveConfigTitle=Do you want to REMOVE your configuration files (*.yaml)?%n%nThis includes your custom rank scaling settings and award configurations.%n%nClick YES to remove configuration files.%nClick NO to keep them.
english.RemoveBackupTitle=Do you want to REMOVE your backup files?%n%nThis includes:%n  - campaignsstates_*.backup%n  - campaign_popups_seen_*.backup%n  - campaignsstates_hash_index.json%n%nThese allow you to restore previous campaign states if you reinstall.%n%nClick YES to remove backup files.%nClick NO to keep them.
english.RemoveServiceRecordTitle=Do you want to REMOVE your Campaign Service Record data?%n%nThis includes:%n  - Pilot photos%n  - Personal information (name, birthday, birthplace)%n%nLocation: %%LOCALAPPDATA%%\.il2_campaign_service_record%n%nClick YES to remove Service Record data.%nClick NO to keep it.

; ============================================================================
; GERMAN
; ============================================================================
german.SelectIL2Folder=Bitte wählen Sie einen existierenden IL-2 Great Battles Installationsordner.
german.InvalidIL2Folder=Der ausgewählte Ordner scheint keine gültige IL-2 Great Battles Installation zu sein.%nBitte wählen Sie das korrekte Spielverzeichnis.
german.RemoveConfigTitle=Möchten Sie Ihre Konfigurationsdateien (*.yaml) ENTFERNEN?%n%nDies umfasst Ihre benutzerdefinierten Rang-Skalierungseinstellungen und Auszeichnungskonfigurationen.%n%nKlicken Sie JA, um die Konfigurationsdateien zu entfernen.%nKlicken Sie NEIN, um sie zu behalten.
german.RemoveBackupTitle=Möchten Sie Ihre Backup-Dateien ENTFERNEN?%n%nDies umfasst:%n  - campaignsstates_*.backup%n  - campaign_popups_seen_*.backup%n  - campaignsstates_hash_index.json%n%nDiese ermöglichen die Wiederherstellung früherer Kampagnenstände bei einer Neuinstallation.%n%nKlicken Sie JA, um die Backup-Dateien zu entfernen.%nKlicken Sie NEIN, um sie zu behalten.
german.RemoveServiceRecordTitle=Möchten Sie Ihre Campaign Service Record Daten ENTFERNEN?%n%nDies umfasst:%n  - Pilotenfotos%n  - Persönliche Informationen (Name, Geburtstag, Geburtsort)%n%nSpeicherort: %%LOCALAPPDATA%%\.il2_campaign_service_record%n%nKlicken Sie JA, um die Service Record Daten zu entfernen.%nKlicken Sie NEIN, um sie zu behalten.

; ============================================================================
; FRENCH
; ============================================================================
french.SelectIL2Folder=Veuillez sélectionner un dossier d'installation IL-2 Great Battles existant.
french.InvalidIL2Folder=Le dossier sélectionné ne semble pas être une installation valide d'IL-2 Great Battles.%nVeuillez sélectionner le répertoire d'installation correct.
french.RemoveConfigTitle=Voulez-vous SUPPRIMER vos fichiers de configuration (*.yaml) ?%n%nCela inclut vos paramètres de progression de rang et configurations de décorations.%n%nCliquez OUI pour supprimer les fichiers de configuration.%nCliquez NON pour les conserver.
french.RemoveBackupTitle=Voulez-vous SUPPRIMER vos fichiers de sauvegarde ?%n%nCela inclut :%n  - campaignsstates_*.backup%n  - campaign_popups_seen_*.backup%n  - campaignsstates_hash_index.json%n%nCeux-ci permettent de restaurer les états de campagne précédents si vous réinstallez.%n%nCliquez OUI pour supprimer les fichiers de sauvegarde.%nCliquez NON pour les conserver.
french.RemoveServiceRecordTitle=Voulez-vous SUPPRIMER vos données Campaign Service Record ?%n%nCela inclut :%n  - Photos de pilote%n  - Informations personnelles (nom, date de naissance, lieu de naissance)%n%nEmplacement : %%LOCALAPPDATA%%\.il2_campaign_service_record%n%nCliquez OUI pour supprimer les données Service Record.%nCliquez NON pour les conserver.

; ============================================================================
; SPANISH
; ============================================================================
spanish.SelectIL2Folder=Por favor, seleccione una carpeta de instalación existente de IL-2 Great Battles.
spanish.InvalidIL2Folder=La carpeta seleccionada no parece ser una instalación válida de IL-2 Great Battles.%nPor favor, seleccione el directorio de instalación correcto.
spanish.RemoveConfigTitle=¿Desea ELIMINAR sus archivos de configuración (*.yaml)?%n%nEsto incluye sus ajustes de escalado de rangos y configuraciones de condecoraciones.%n%nHaga clic en SÍ para eliminar los archivos de configuración.%nHaga clic en NO para conservarlos.
spanish.RemoveBackupTitle=¿Desea ELIMINAR sus archivos de respaldo?%n%nEsto incluye:%n  - campaignsstates_*.backup%n  - campaign_popups_seen_*.backup%n  - campaignsstates_hash_index.json%n%nEstos permiten restaurar estados de campaña anteriores si reinstala.%n%nHaga clic en SÍ para eliminar los archivos de respaldo.%nHaga clic en NO para conservarlos.
spanish.RemoveServiceRecordTitle=¿Desea ELIMINAR sus datos de Campaign Service Record?%n%nEsto incluye:%n  - Fotos de piloto%n  - Información personal (nombre, fecha de nacimiento, lugar de nacimiento)%n%nUbicación: %%LOCALAPPDATA%%\.il2_campaign_service_record%n%nHaga clic en SÍ para eliminar los datos de Service Record.%nHaga clic en NO para conservarlos.

; ============================================================================
; POLISH
; ============================================================================
polish.SelectIL2Folder=Proszę wybrać istniejący folder instalacji IL-2 Great Battles.
polish.InvalidIL2Folder=Wybrany folder nie wydaje się być prawidłową instalacją IL-2 Great Battles.%nProszę wybrać właściwy katalog instalacji gry.
polish.RemoveConfigTitle=Czy chcesz USUNĄĆ pliki konfiguracyjne (*.yaml)?%n%nObejmuje to niestandardowe ustawienia skalowania rang i konfiguracje odznaczeń.%n%nKliknij TAK, aby usunąć pliki konfiguracyjne.%nKliknij NIE, aby je zachować.
polish.RemoveBackupTitle=Czy chcesz USUNĄĆ pliki kopii zapasowych?%n%nObejmuje to:%n  - campaignsstates_*.backup%n  - campaign_popups_seen_*.backup%n  - campaignsstates_hash_index.json%n%nPozwalają one przywrócić poprzednie stany kampanii po ponownej instalacji.%n%nKliknij TAK, aby usunąć pliki kopii zapasowych.%nKliknij NIE, aby je zachować.
polish.RemoveServiceRecordTitle=Czy chcesz USUNĄĆ dane Campaign Service Record?%n%nObejmuje to:%n  - Zdjęcia pilotów%n  - Dane osobowe (imię, data urodzenia, miejsce urodzenia)%n%nLokalizacja: %%LOCALAPPDATA%%\.il2_campaign_service_record%n%nKliknij TAK, aby usunąć dane Service Record.%nKliknij NIE, aby je zachować.

; ============================================================================
; RUSSIAN
; ============================================================================
russian.SelectIL2Folder=Пожалуйста, выберите существующую папку установки IL-2 Great Battles.
russian.InvalidIL2Folder=Выбранная папка не является корректной установкой IL-2 Great Battles.%nПожалуйста, выберите правильный каталог установки игры.
russian.RemoveConfigTitle=Хотите УДАЛИТЬ файлы конфигурации (*.yaml)?%n%nЭто включает ваши настройки масштабирования званий и конфигурации наград.%n%nНажмите ДА, чтобы удалить файлы конфигурации.%nНажмите НЕТ, чтобы сохранить их.
russian.RemoveBackupTitle=Хотите УДАЛИТЬ файлы резервных копий?%n%nЭто включает:%n  - campaignsstates_*.backup%n  - campaign_popups_seen_*.backup%n  - campaignsstates_hash_index.json%n%nОни позволяют восстановить предыдущие состояния кампаний при переустановке.%n%nНажмите ДА, чтобы удалить файлы резервных копий.%nНажмите НЕТ, чтобы сохранить их.
russian.RemoveServiceRecordTitle=Хотите УДАЛИТЬ данные Campaign Service Record?%n%nЭто включает:%n  - Фотографии пилотов%n  - Личную информацию (имя, дата рождения, место рождения)%n%nРасположение: %%LOCALAPPDATA%%\.il2_campaign_service_record%n%nНажмите ДА, чтобы удалить данные Service Record.%nНажмите НЕТ, чтобы сохранить их.

; ============================================================================
; CHINESE SIMPLIFIED
; ============================================================================
chinesesimplified.SelectIL2Folder=请选择现有的 IL-2 Great Battles 安装文件夹。
chinesesimplified.InvalidIL2Folder=所选文件夹似乎不是有效的 IL-2 Great Battles 安装。%n请选择正确的游戏安装目录。
chinesesimplified.RemoveConfigTitle=您要删除配置文件 (*.yaml) 吗？%n%n这包括您的自定义军衔缩放设置和勋章配置。%n%n点击"是"删除配置文件。%n点击"否"保留它们。
chinesesimplified.RemoveBackupTitle=您要删除备份文件吗？%n%n这包括：%n  - campaignsstates_*.backup%n  - campaign_popups_seen_*.backup%n  - campaignsstates_hash_index.json%n%n这些文件允许您在重新安装时恢复以前的战役状态。%n%n点击"是"删除备份文件。%n点击"否"保留它们。
chinesesimplified.RemoveServiceRecordTitle=您要删除 Campaign Service Record 数据吗？%n%n这包括：%n  - 飞行员照片%n  - 个人信息（姓名、生日、出生地）%n%n位置：%%LOCALAPPDATA%%\.il2_campaign_service_record%n%n点击"是"删除 Service Record 数据。%n点击"否"保留它们。

[Tasks]
Name: "desktopicon"; Description: "Create a &desktop icon"; GroupDescription: "Additional icons:"; Flags: unchecked

[Files]
; --- Tracker install folder ({app}) ---
; Font file for PDF export
Source: "IBMPlexSans-Light.ttf"; DestDir: "{app}"; Flags: ignoreversion
Source: "NotoSansSC-VF.ttf"; DestDir: "{app}"; Flags: ignoreversion

; Configuration files: only install if not already present (preserves user settings)
Source: "campaign_progress_config.yaml"; DestDir: "{app}"; Flags: onlyifdoesntexist uninsneveruninstall
Source: "object_categories.yaml"; DestDir: "{app}"; Flags: onlyifdoesntexist uninsneveruninstall
Source: "stock_campaigns.yaml"; DestDir: "{app}"; Flags: onlyifdoesntexist uninsneveruninstall

; Program files: always overwrite
Source: "IL2_CampaignTracker_v2.1_ML.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "mlg2txt.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "QUICK_START.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "README.html"; DestDir: "{app}"; Flags: ignoreversion

; i18n translation files
Source: "locales\*.json"; DestDir: "{app}\locales"; Flags: ignoreversion

; --- Campaign Service Record ---
Source: "Campaign_Service_Record.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "_internal\*"; DestDir: "{app}\_internal"; Flags: recursesubdirs createallsubdirs ignoreversion

; --- Cleanup utility for uninstaller ---
Source: "cleanup_tracker_content.exe"; DestDir: "{app}"; Flags: ignoreversion

; --- Copy CampaignRanksAwards into IL-2 ---
; This places content into: <IL-2>\data\swf\CampaignRanksAwards\*
Source: "CampaignRanksAwards\*"; DestDir: "{code:GetIL2DataSwfDir}\CampaignRanksAwards"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\Campaign Service Record"; Filename: "{app}\Campaign_Service_Record.exe"
Name: "{group}\Uninstall"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "Launch {#MyAppName}"; Flags: nowait postinstall skipifsilent

[Code]
var
  IL2PathPage: TInputDirWizardPage;
  RemoveConfigFiles: Boolean;
  RemoveBackupFiles: Boolean;
  RemoveServiceRecordData: Boolean;

function IsIL2Folder(const DirPath: string): Boolean;
var
  DataPath: string;
begin
  Result := False;
  DataPath := AddBackslash(DirPath) + 'data';
  if DirExists(DataPath) then
    Result := True;
end;

procedure InitializeWizard;
begin
  IL2PathPage := CreateInputDirPage(
    wpSelectDir,
    ExpandConstant('{cm:SelectIL2Folder}'),
    '',
    '',
    False,
    ''
  );
  IL2PathPage.Add('');
end;

function NormalizeDir(const DirPath: string): string;
begin
  Result := ExcludeTrailingPathDelimiter(Trim(DirPath));
end;

function NextButtonClick(CurPageID: Integer): Boolean;
var
  NormalPath: string;
begin
  Result := True;
  if CurPageID = IL2PathPage.ID then
  begin
    NormalPath := NormalizeDir(IL2PathPage.Values[0]);
    if not IsIL2Folder(NormalPath) then
    begin
      MsgBox(ExpandConstant('{cm:InvalidIL2Folder}'), mbError, MB_OK);
      Result := False;
    end
    else
    begin
      IL2PathPage.Values[0] := NormalPath;
    end;
  end;
end;

function GetIL2Path(Param: string): string;
begin
  Result := NormalizeDir(IL2PathPage.Values[0]);
end;

function GetIL2DataSwfDir(Param: string): string;
begin
  Result := AddBackslash(GetIL2Path('')) + 'data\swf';
end;

procedure RegisterIL2Path();
var
  IL2Root: string;
begin
  IL2Root := NormalizeDir(IL2PathPage.Values[0]);
  RegWriteStringValue(HKCU, 'Software\IL2CampaignTracker', 'IL2Path', IL2Root);
end;

function GetStoredIL2Path(): string;
begin
  if not RegQueryStringValue(HKCU, 'Software\IL2CampaignTracker', 'IL2Path', Result) then
    Result := '';
end;

procedure CurStepChanged(CurStep: TInstallStep);
begin
  if CurStep = ssPostInstall then
  begin
    RegisterIL2Path();
  end;
end;

function InitializeUninstall(): Boolean;
var
  ResultCode: Integer;
begin
  Result := True;

  { Ask user about config files }
  ResultCode := MsgBox(ExpandConstant('{cm:RemoveConfigTitle}'), mbConfirmation, MB_YESNO);
  RemoveConfigFiles := (ResultCode = IDYES);

  { Ask user about backup files }
  ResultCode := MsgBox(ExpandConstant('{cm:RemoveBackupTitle}'), mbConfirmation, MB_YESNO);
  RemoveBackupFiles := (ResultCode = IDYES);

  { Ask user about Service Record data }
  ResultCode := MsgBox(ExpandConstant('{cm:RemoveServiceRecordTitle}'), mbConfirmation, MB_YESNO);
  RemoveServiceRecordData := (ResultCode = IDYES);
end;

procedure DeleteUserSaveCampaignFiles(const IL2Root: string);
var
  UserSaveDir, CampaignDir: string;
  FindRec: TFindRec;
begin
  { <IL-2>\data\Campaigns\usersave }
  UserSaveDir := AddBackslash(IL2Root) + 'data\Campaigns\usersave';
  
  if not DirExists(UserSaveDir) then
    Exit;

  { Iterate through each UUID campaign folder }
  if FindFirst(UserSaveDir + '\*', FindRec) then
  try
    repeat
      if (FindRec.Attributes and FILE_ATTRIBUTE_DIRECTORY) <> 0 then
      begin
        if (FindRec.Name <> '.') and (FindRec.Name <> '..') then
        begin
          CampaignDir := UserSaveDir + '\' + FindRec.Name;

          if RemoveBackupFiles then
          begin
            { Wildcard deletes – ignore errors }
            DelTree(CampaignDir + '\campaignsstates_*.backup', False, True, False);
            DelTree(CampaignDir + '\campaign_popups_seen_*.backup', False, True, False);

            { Single file }
            DeleteFile(CampaignDir + '\campaignsstates_hash_index.json');
          end;
        end;
      end;
    until not FindNext(FindRec);
  finally
    FindClose(FindRec);
  end;
end;

procedure RestoreCampaignInfoBackups(const IL2Root: string);
var
  CampaignsDir, CampaignDir: string;
  FindRecCampaign, FindRecFile: TFindRec;
  BackupFile, OriginalFile: string;
  HasBackups: Boolean;
begin
  { <IL-2>\data\Campaigns }
  CampaignsDir := AddBackslash(IL2Root) + 'data\Campaigns';
  
  if not DirExists(CampaignsDir) then
    Exit;

  { Iterate through each campaign folder }
  if FindFirst(CampaignsDir + '\*', FindRecCampaign) then
  try
    repeat
      if (FindRecCampaign.Attributes and FILE_ATTRIBUTE_DIRECTORY) <> 0 then
      begin
        if (FindRecCampaign.Name <> '.') and (FindRecCampaign.Name <> '..') and (FindRecCampaign.Name <> 'usersave') then
        begin
          CampaignDir := CampaignsDir + '\' + FindRecCampaign.Name;
          HasBackups := False;

          { Check if this campaign has any .backup files }
          if FindFirst(CampaignDir + '\*.backup', FindRecFile) then
          try
            HasBackups := True;
          finally
            FindClose(FindRecFile);
          end;

          { Only process campaigns with backup files }
          if HasBackups then
          begin
            { Delete all info.locale=*.txt files (without .backup extension) }
            if FindFirst(CampaignDir + '\info.locale=*.txt', FindRecFile) then
            try
              repeat
                if (FindRecFile.Attributes and FILE_ATTRIBUTE_DIRECTORY) = 0 then
                begin
                  OriginalFile := CampaignDir + '\' + FindRecFile.Name;
                  { Only delete if it's NOT a backup file }
                  if Pos('.backup', LowerCase(OriginalFile)) = 0 then
                  begin
                    DeleteFile(OriginalFile);
                  end;
                end;
              until not FindNext(FindRecFile);
            finally
              FindClose(FindRecFile);
            end;

            { Rename all *.backup files to remove .backup extension }
            if FindFirst(CampaignDir + '\info.locale=*.txt.backup', FindRecFile) then
            try
              repeat
                if (FindRecFile.Attributes and FILE_ATTRIBUTE_DIRECTORY) = 0 then
                begin
                  BackupFile := CampaignDir + '\' + FindRecFile.Name;
                  OriginalFile := Copy(BackupFile, 1, Length(BackupFile) - Length('.backup'));
                  RenameFile(BackupFile, OriginalFile);
                end;
              until not FindNext(FindRecFile);
            finally
              FindClose(FindRecFile);
            end;
          end;
        end;
      end;
    until not FindNext(FindRecCampaign);
  finally
    FindClose(FindRecCampaign);
  end;
end;

procedure DeleteServiceRecordData();
var
  ServiceRecordDir: string;
begin
  if not RemoveServiceRecordData then
  begin
    { User wants to keep Service Record data - skip this step }
    Exit;
  end;

  { Get %LOCALAPPDATA%\.il2_campaign_service_record }
  ServiceRecordDir := ExpandConstant('{localappdata}\.il2_campaign_service_record');
  
  if DirExists(ServiceRecordDir) then
  begin
    { Delete entire directory including:
      - pilot_photos/
      - campaign_personal_data.json }
    DelTree(ServiceRecordDir, True, True, True);
  end;
end;

procedure RunCleanupTrackerContent(const IL2Root: string);
var
  CleanupExe: string;
  ResultCode: Integer;
begin
  { Run cleanup_tracker_content.exe to remove Events/Debriefings from info.locale files }
  CleanupExe := ExpandConstant('{app}\cleanup_tracker_content.exe');
  
  if FileExists(CleanupExe) then
  begin
    { Run silently with --quiet flag }
    Exec(CleanupExe, '--uninstall --quiet --il2-path "' + IL2Root + '"', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
    { Ignore result code - cleanup is best-effort }
  end;
end;

procedure DeleteAppFiles();
var
  AppDir: string;
  FindRec: TFindRec;
  FilePath, FileExt: string;
begin
  AppDir := ExpandConstant('{app}');
  
  if not DirExists(AppDir) then
    Exit;
    
  { Find and delete files based on extension }
  if FindFirst(AppDir + '\*', FindRec) then
  try
    repeat
      if (FindRec.Attributes and FILE_ATTRIBUTE_DIRECTORY) = 0 then
      begin
        FilePath := AppDir + '\' + FindRec.Name;
        FileExt := LowerCase(ExtractFileExt(FindRec.Name));
        
        { Keep *.yaml files unless user chose to remove config }
        if (not RemoveConfigFiles) and (FileExt = '.yaml') then
        begin
          { Keep this file }
        end
        else
        begin
          { Delete all other files: *.json, *.log, *.exe, *.txt, *.html, *.ttf, etc. }
          DeleteFile(FilePath);
        end;
      end;
    until not FindNext(FindRec);
  finally
    FindClose(FindRec);
  end;
  
  { Delete subdirectories }
  DelTree(AppDir + '\reports', True, True, True);
  DelTree(AppDir + '\_internal', True, True, True);
  DelTree(AppDir + '\locales', True, True, True);
  
  { Try to remove the app directory if empty (will fail if config files kept) }
  RemoveDir(AppDir);
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
  IL2Root, AwardsDir: string;
begin
  if CurUninstallStep = usUninstall then
  begin
    IL2Root := NormalizeDir(GetStoredIL2Path());

    if (IL2Root <> '') and DirExists(IL2Root) then
    begin
      { Step 1: Remove tracker content from info.locale files }
      RunCleanupTrackerContent(IL2Root);
    
      { Step 2: Restore backup files in campaign folders }
      { This restores original info.locale=*.txt files from .backup versions }
      RestoreCampaignInfoBackups(IL2Root);

      { Step 3: Remove CampaignRanksAwards folder }
      AwardsDir := IL2Root + '\data\swf\CampaignRanksAwards';
      if DirExists(AwardsDir) then
        DelTree(AwardsDir, True, True, True);

      { Step 4: Remove tracker-related files from usersave UUID campaign folders }
      { (respects RemoveBackupFiles setting) }
      DeleteUserSaveCampaignFiles(IL2Root);
    end;
    
    { Step 5: Delete Campaign Service Record data }
    { (respects RemoveServiceRecordData setting) }
    DeleteServiceRecordData();
    
    { Step 6: Delete app files (respects RemoveConfigFiles setting) }
    { Deletes: *.json, *.log, *.exe, *.txt, *.html, *.ttf, _internal\, locales\ }
    { Keeps: *.yaml (unless RemoveConfigFiles = True) }
    DeleteAppFiles();
  end;
end;
