; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
#define MyAppName "IL-2 Great Battles SP Campaign Tracker"
#define MyAppExeName "IL2_CampaignTracker_v2.0.exe"
#define MyAppVersion "2.0"
#define MyAppPublisher "Arrow_1"

[Setup]
AppId={{1c17a2fd-8f7a-424f-b1b6-702505698a52}}  ; <-- change to a real GUID and keep it stable
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}

[Setup]
PrivilegesRequired=admin
DefaultDirName={localappdata}\{#MyAppName}
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes

OutputBaseFilename=IL2_CampaignTracker_Setup_v{#MyAppVersion}
Compression=lzma
SolidCompression=yes

UsePreviousAppDir=yes

UninstallDisplayName=IL-2 Great Battles SP Campaign Tracker Uninstaller
UninstallDisplayIcon={app}\IL2_CampaignTracker_v2.0.exe

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "Create a &desktop icon"; GroupDescription: "Additional icons:"; Flags: unchecked

[Files]
; --- Tracker install folder ({app}) ---
Source: "campaign_progress_config.yaml"; DestDir: "{app}"; Flags: ignoreversion
Source: "IL2_CampaignTracker_v2.0.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "mlg2txt.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "object_categories.yaml"; DestDir: "{app}"; Flags: ignoreversion
Source: "QUICK_START.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "README.html"; DestDir: "{app}"; Flags: ignoreversion
Source: "stock_campaigns.yaml"; DestDir: "{app}"; Flags: ignoreversion

; --- Copy CampaignRanksAwards into IL-2 ---
; This places content into: <IL-2>\data\swf\CampaignRanksAwards\*
Source: "CampaignRanksAwards\*"; DestDir: "{code:GetIL2Dir}\data\swf\CampaignRanksAwards"; Flags: recursesubdirs createallsubdirs ignoreversion

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon
Name: "{group}\Uninstall IL-2 Campaign Tracker"; Filename: "{uninstallexe}"


[Registry]
; Store IL-2 install path for uninstall cleanup
Root: HKLM; Subkey: "Software\{#MyAppName}"; ValueType: string; ValueName: "IL2Path"; ValueData: "{code:GetIL2Dir}"; Flags: uninsdeletekey

[UninstallDelete]
; Delete entire installation folder on uninstall
Type: filesandordirs; Name: "{app}"

[Code]

var
  IL2DirPage: TInputDirWizardPage;
  IL2DirValue: string;

{ ----------------------------
  Helpers
  ---------------------------- }

function NormalizeDir(const S: string): string;
begin
  Result := Trim(S);
  while (Length(Result) > 0) and (Result[Length(Result)] = '\') do
    Delete(Result, Length(Result), 1);
end;

function LooksLikeIL2Root(const Dir: string): Boolean;
begin
  { Keep this check internal (do not mention it in UI text).
    Adjust markers if needed. These are safe and lightweight. }
  Result :=
    DirExists(Dir + '\data') and
    DirExists(Dir + '\data\swf');
end;

function GetStoredIL2Path(): string;
begin
  Result := '';

  { Prefer 64-bit HKLM view (recommended write target) }
  if not RegQueryStringValue(HKLM64, 'Software\{#MyAppName}', 'IL2Path', Result) then
  begin
    { Fallback: 32-bit view (WOW6432Node) for legacy installs }
    RegQueryStringValue(HKLM32, 'Software\{#MyAppName}', 'IL2Path', Result);
  end;
end;

function GetIL2Dir(Param: string): string;
begin
  // Used by [Files]/[Registry] as {code:GetIL2Dir} 
  Result := IL2DirValue;

  { Fallback (e.g., edge cases) }
  if Result = '' then
    Result := GetStoredIL2Path();
end;

procedure PrefillIL2Dir;
var
  Prev: string;
  DefaultSteamIL2: string;
begin
  Prev := NormalizeDir(GetStoredIL2Path());
  DefaultSteamIL2 :=
    'C:\Program Files (x86)\Steam\steamapps\common\IL-2 Sturmovik Battle of Stalingrad';

  if (Prev <> '') and DirExists(Prev) then
    IL2DirPage.Values[0] := Prev
  else if DirExists(DefaultSteamIL2) then
    IL2DirPage.Values[0] := DefaultSteamIL2
  else
    IL2DirPage.Values[0] := 'C:\Program Files (x86)\Steam\steamapps\common';
end;

{ ----------------------------
  Wizard setup
  ---------------------------- }

procedure InitializeWizard;
begin
  IL2DirPage := CreateInputDirPage(
    wpSelectDir,
    'Select IL-2 Great Battles Installation Folder',
    'Choose the folder where IL-2 Great Battles is installed.',
    'Please select the main IL-2 Great Battles installation directory.',
    False,
    ''
  );

  // Create the first (and only) directory input row
  IL2DirPage.Add('');

  PrefillIL2Dir();
end;


function NextButtonClick(CurPageID: Integer): Boolean;
var
  D: string;
begin
  Result := True;

  if CurPageID = IL2DirPage.ID then
  begin
    D := NormalizeDir(IL2DirPage.Values[0]);

    if (D = '') or (not DirExists(D)) then
    begin
      MsgBox('Please select an existing IL-2 Great Battles installation folder.', mbError, MB_OK);
      Result := False;
      Exit;
    end;

    if not LooksLikeIL2Root(D) then
    begin
      MsgBox(
        'The selected folder does not appear to be a valid IL-2 Great Battles installation.' + #13#10 +
        'Please select the correct game installation directory.',
        mbError,
        MB_OK
      );
      Result := False;
      Exit;
    end;

    { Store for this run }
    IL2DirValue := D;
  end;
end;

// ----------------------------
//  Uninstall cleanup
//  - Deletes:
//    1) <IL-2>\data\swf\CampaignRanksAwards\*
//    2) For each UUID folder:
//       <IL-2>\data\swf\il2\usersave\{UUID}\campaign\
//         - campaignsstates_*.backup
//         - campaign_popups_seen_*.backup
//         - campaignsstates_hash_index.json
//  Note: Your [UninstallDelete] can delete {app} completely.
//  ---------------------------- 

procedure DeleteUserSaveCampaignFiles(const IL2Root: string);
var
  UsersaveRoot, SearchPath, UUIDDir, CampaignDir: string;
  FindRec: TFindRec;
begin
  UsersaveRoot := IL2Root + '\data\swf\il2\usersave';
  if not DirExists(UsersaveRoot) then
    Exit;

  SearchPath := UsersaveRoot + '\*';
  if FindFirst(SearchPath, FindRec) then
  try
    repeat
      if (FindRec.Attributes and FILE_ATTRIBUTE_DIRECTORY) <> 0 then
      begin
        if (FindRec.Name <> '.') and (FindRec.Name <> '..') then
        begin
          UUIDDir := UsersaveRoot + '\' + FindRec.Name;
          CampaignDir := UUIDDir + '\campaign';

          if DirExists(CampaignDir) then
          begin
            { Wildcard deletes – ignore errors }
            DelTree(CampaignDir + '\campaignsstates_*.backup', False, True, False);
            DelTree(CampaignDir + '\campaign_popups_seen_*.backup', False, True, False);

            { Single file }
            DeleteFile(CampaignDir + '\campaignsstates_hash_index.json');
          end;
        end;
      end;
    until not FindNext(FindRec);
  finally
    FindClose(FindRec);
  end;
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
  IL2Root, AwardsDir: string;
begin
  if CurUninstallStep = usUninstall then
  begin
    IL2Root := NormalizeDir(GetStoredIL2Path());

    if (IL2Root <> '') and DirExists(IL2Root) then
    begin
      { Remove CampaignRanksAwards folder }
      AwardsDir := IL2Root + '\data\swf\CampaignRanksAwards';
      if DirExists(AwardsDir) then
        DelTree(AwardsDir, True, True, True);

      { Remove tracker-related files from usersave UUID campaign folders }
      DeleteUserSaveCampaignFiles(IL2Root);
    end;
  end;
end;


