; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
#define MyAppName "IL-2 Great Battles SP Campaign Tracker Multi Language"
#define MyAppExeName "IL2_Tracker_Control_GUI.exe"
#define MyAppVersion "2.2.6"
#define MyAppPublisher "Arrow_1"

[Setup]
AppId={{1c17a2fd-8f7a-424f-b1b6-702505698a52}}  ; <-- change to a real GUID and keep it stable
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
PrivilegesRequired=admin
DefaultDirName={localappdata}\{#MyAppName}
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes

OutputBaseFilename=IL2_CampaignTracker_Setup_v{#MyAppVersion}_ML
Compression=lzma
SolidCompression=yes

UsePreviousAppDir=yes

UninstallDisplayName=IL-2 Great Battles SP Campaign Tracker Uninstaller
UninstallDisplayIcon={app}\IL2_CampaignTracker_v2.2_ML.exe

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "german"; MessagesFile: "compiler:Languages\German.isl"
Name: "french"; MessagesFile: "compiler:Languages\French.isl"
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"
Name: "polish"; MessagesFile: "compiler:Languages\Polish.isl"
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"
Name: "chinesesimplified"; MessagesFile: "compiler:Languages\ChineseSimplified.isl"

[CustomMessages]
; ============================================================================
; ENGLISH (default)
; ============================================================================
english.SelectIL2Folder=Please select an existing IL-2 Great Battles installation folder.
english.InvalidIL2Folder=The selected folder does not appear to be a valid IL-2 Great Battles installation.%nPlease select the correct game installation directory.
english.RemoveConfigTitle=Do you want to REMOVE your configuration files (*.yaml)?%n%nThis includes your custom rank scaling settings and award configurations.%n%nClick YES to remove configuration files.%nClick NO to keep them.
english.RemoveBackupTitle=Do you want to REMOVE your backup files?%n%nThis includes:%n  - campaignsstates_*.backup%n  - campaign_popups_seen_*.backup%n  - campaignsstates_hash_index.json%n%nThese allow you to restore previous campaign states if you reinstall.%n%nClick YES to remove backup files.%nClick NO to keep them.
english.RemoveServiceRecordTitle=Do you want to REMOVE your Campaign Service Record data?%n%nThis includes:%n  - Pilot photos%n  - Personal information (name, birthday, birthplace)%n  - AI story chapters%n%nLocation: %%LOCALAPPDATA%%\.il2_campaign_service_record%n%nClick YES to remove Service Record data.%nClick NO to keep it.
english.RemoveFlightLogsTitle=Do you want to REMOVE the generated flight log files (*.txt, *.json)?%n%nThis includes all *.txt and *.json files in:%n  <IL-2 game folder>\data\FlightLogs%n%nThese files were created by the tracker and are regenerated on the next run.%n%nClick YES to remove flight log files.%nClick NO to keep them.
english.IL2PageTitle=Select IL-2 Great Battles Installation Folder
english.IL2PageDescription=Choose the folder where IL-2 Great Battles is installed.
english.IL2PagePrompt=Please select the main IL-2 Great Battles installation directory.
english.AdditionalIcons=Additional icons:
english.CreateDesktopIcon=Create a &desktop icon
english.GermanAwardsGroupDesc=German awards style:
english.GermanAwards1957=1957 version (Bundeswehr-era, default)
english.GermanAwardsWW2=Original WW2-era German awards

; ============================================================================
; GERMAN
; ============================================================================
german.SelectIL2Folder=Bitte wählen Sie einen existierenden IL-2 Great Battles Installationsordner.
german.InvalidIL2Folder=Der ausgewählte Ordner scheint keine gültige IL-2 Great Battles Installation zu sein.%nBitte wählen Sie das korrekte Spielverzeichnis.
german.RemoveConfigTitle=Möchten Sie Ihre Konfigurationsdateien (*.yaml) ENTFERNEN?%n%nDies umfasst Ihre benutzerdefinierten Rang-Skalierungseinstellungen und Auszeichnungskonfigurationen.%n%nKlicken Sie JA, um die Konfigurationsdateien zu entfernen.%nKlicken Sie NEIN, um sie zu behalten.
german.RemoveBackupTitle=Möchten Sie Ihre Backup-Dateien ENTFERNEN?%n%nDies umfasst:%n  - campaignsstates_*.backup%n  - campaign_popups_seen_*.backup%n  - campaignsstates_hash_index.json%n%nDiese ermöglichen die Wiederherstellung früherer Kampagnenstände bei einer Neuinstallation.%n%nKlicken Sie JA, um die Backup-Dateien zu entfernen.%nKlicken Sie NEIN, um sie zu behalten.
german.RemoveServiceRecordTitle=Möchten Sie Ihre Campaign Service Record Daten ENTFERNEN?%n%nDies umfasst:%n  - Pilotenfotos%n  - Persönliche Informationen (Name, Geburtstag, Geburtsort)%n  - KI-Story-Kapitel%n%nSpeicherort: %%LOCALAPPDATA%%\.il2_campaign_service_record%n%nKlicken Sie JA, um die Service Record Daten zu entfernen.%nKlicken Sie NEIN, um sie zu behalten.
german.RemoveFlightLogsTitle=Möchten Sie die generierten Flugprotokoll-Dateien ENTFERNEN (*.txt, *.json)?%n%nDies umfasst alle *.txt und *.json Dateien in:%n  <IL-2 Spielordner>\data\FlightLogs%n%nDiese Dateien wurden vom Tracker erstellt und werden beim nächsten Start neu generiert.%n%nKlicken Sie JA, um die Flugprotokoll-Dateien zu entfernen.%nKlicken Sie NEIN, um sie zu behalten.
german.IL2PageTitle=IL-2 Great Battles Installationsordner auswählen
german.IL2PageDescription=Wählen Sie den Ordner, in dem IL-2 Great Battles installiert ist.
german.IL2PagePrompt=Bitte wählen Sie das Hauptinstallationsverzeichnis von IL-2 Great Battles.
german.AdditionalIcons=Zusätzliche Symbole:
german.CreateDesktopIcon=&Desktop-Symbol erstellen
german.GermanAwardsGroupDesc=Stil der deutschen Auszeichnungen:
german.GermanAwards1957=Version 1957 (Bundeswehr-Ära, Standard)
german.GermanAwardsWW2=Originale deutsche Auszeichnungen (2. Weltkrieg)

; ============================================================================
; FRENCH
; ============================================================================
french.SelectIL2Folder=Veuillez sélectionner un dossier d'installation IL-2 Great Battles existant.
french.InvalidIL2Folder=Le dossier sélectionné ne semble pas être une installation valide d'IL-2 Great Battles.%nVeuillez sélectionner le répertoire d'installation correct.
french.RemoveConfigTitle=Voulez-vous SUPPRIMER vos fichiers de configuration (*.yaml) ?%n%nCela inclut vos paramètres de progression de rang et configurations de décorations.%n%nCliquez OUI pour supprimer les fichiers de configuration.%nCliquez NON pour les conserver.
french.RemoveBackupTitle=Voulez-vous SUPPRIMER vos fichiers de sauvegarde ?%n%nCela inclut :%n  - campaignsstates_*.backup%n  - campaign_popups_seen_*.backup%n  - campaignsstates_hash_index.json%n%nCeux-ci permettent de restaurer les états de campagne précédents si vous réinstallez.%n%nCliquez OUI pour supprimer les fichiers de sauvegarde.%nCliquez NON pour les conserver.
french.RemoveServiceRecordTitle=Voulez-vous SUPPRIMER vos données Campaign Service Record ?%n%nCela inclut :%n  - Photos de pilote%n  - Informations personnelles (nom, date de naissance, lieu de naissance)%n  - Chapitres d'histoires IA%n%nEmplacement : %%LOCALAPPDATA%%\.il2_campaign_service_record%n%nCliquez OUI pour supprimer les données Service Record.%nCliquez NON pour les conserver.
french.RemoveFlightLogsTitle=Voulez-vous SUPPRIMER les fichiers de journal de vol générés (*.txt, *.json) ?%n%nCela inclut tous les fichiers *.txt et *.json dans :%n  <dossier du jeu IL-2>\data\FlightLogs%n%nCes fichiers ont été créés par le tracker et sont régénérés au prochain démarrage.%n%nCliquez OUI pour supprimer les fichiers de journal de vol.%nCliquez NON pour les conserver.
french.IL2PageTitle=Sélectionner le dossier d'installation d'IL-2 Great Battles
french.IL2PageDescription=Choisissez le dossier où IL-2 Great Battles est installé.
french.IL2PagePrompt=Veuillez sélectionner le répertoire d'installation principal d'IL-2 Great Battles.
french.AdditionalIcons=Icônes supplémentaires :
french.CreateDesktopIcon=Créer une icône sur le &bureau
french.GermanAwardsGroupDesc=Style des décorations allemandes :
french.GermanAwards1957=Version 1957 (ère Bundeswehr, par défaut)
french.GermanAwardsWW2=Décorations allemandes originales de la Seconde Guerre mondiale

; ============================================================================
; SPANISH
; ============================================================================
spanish.SelectIL2Folder=Por favor, seleccione una carpeta de instalación existente de IL-2 Great Battles.
spanish.InvalidIL2Folder=La carpeta seleccionada no parece ser una instalación válida de IL-2 Great Battles.%nPor favor, seleccione el directorio de instalación correcto.
spanish.RemoveConfigTitle=¿Desea ELIMINAR sus archivos de configuración (*.yaml)?%n%nEsto incluye sus ajustes de escalado de rangos y configuraciones de condecoraciones.%n%nHaga clic en SÍ para eliminar los archivos de configuración.%nHaga clic en NO para conservarlos.
spanish.RemoveBackupTitle=¿Desea ELIMINAR sus archivos de respaldo?%n%nEsto incluye:%n  - campaignsstates_*.backup%n  - campaign_popups_seen_*.backup%n  - campaignsstates_hash_index.json%n%nEstos permiten restaurar estados de campaña anteriores si reinstala.%n%nHaga clic en SÍ para eliminar los archivos de respaldo.%nHaga clic en NO para conservarlos.
spanish.RemoveServiceRecordTitle=¿Desea ELIMINAR sus datos de Campaign Service Record?%n%nEsto incluye:%n  - Fotos de piloto%n  - Información personal (nombre, fecha de nacimiento, lugar de nacimiento)%n  - Capítulos de historias IA%n%nUbicación: %%LOCALAPPDATA%%\.il2_campaign_service_record%n%nHaga clic en SÍ para eliminar los datos de Service Record.%nHaga clic en NO para conservarlos.
spanish.RemoveFlightLogsTitle=¿Desea ELIMINAR los archivos de registro de vuelo generados (*.txt, *.json)?%n%nEsto incluye todos los archivos *.txt y *.json en:%n  <carpeta del juego IL-2>\data\FlightLogs%n%nEstos archivos fueron creados por el tracker y se regeneran en el próximo inicio.%n%nHaga clic en SÍ para eliminar los archivos de registro de vuelo.%nHaga clic en NO para conservarlos.
spanish.IL2PageTitle=Seleccionar carpeta de instalación de IL-2 Great Battles
spanish.IL2PageDescription=Elija la carpeta donde está instalado IL-2 Great Battles.
spanish.IL2PagePrompt=Por favor, seleccione el directorio de instalación principal de IL-2 Great Battles.
spanish.AdditionalIcons=Iconos adicionales:
spanish.CreateDesktopIcon=Crear un icono en el &escritorio
spanish.GermanAwardsGroupDesc=Estilo de condecoraciones alemanas:
spanish.GermanAwards1957=Versión 1957 (era Bundeswehr, predeterminado)
spanish.GermanAwardsWW2=Condecoraciones alemanas originales de la Segunda Guerra Mundial

; ============================================================================
; POLISH
; ============================================================================
polish.SelectIL2Folder=Proszę wybrać istniejący folder instalacji IL-2 Great Battles.
polish.InvalidIL2Folder=Wybrany folder nie wydaje się być prawidłową instalacją IL-2 Great Battles.%nProszę wybrać właściwy katalog instalacji gry.
polish.RemoveConfigTitle=Czy chcesz USUNĄĆ pliki konfiguracyjne (*.yaml)?%n%nObejmuje to niestandardowe ustawienia skalowania rang i konfiguracje odznaczeń.%n%nKliknij TAK, aby usunąć pliki konfiguracyjne.%nKliknij NIE, aby je zachować.
polish.RemoveBackupTitle=Czy chcesz USUNĄĆ pliki kopii zapasowych?%n%nObejmuje to:%n  - campaignsstates_*.backup%n  - campaign_popups_seen_*.backup%n  - campaignsstates_hash_index.json%n%nPozwalają one przywrócić poprzednie stany kampanii po ponownej instalacji.%n%nKliknij TAK, aby usunąć pliki kopii zapasowych.%nKliknij NIE, aby je zachować.
polish.RemoveServiceRecordTitle=Czy chcesz USUNĄĆ dane Campaign Service Record?%n%nObejmuje to:%n  - Zdjęcia pilotów%n  - Dane osobowe (imię, data urodzenia, miejsce urodzenia)%n  - Rozdziały historii AI%n%nLokalizacja: %%LOCALAPPDATA%%\.il2_campaign_service_record%n%nKliknij TAK, aby usunąć dane Service Record.%nKliknij NIE, aby je zachować.
polish.RemoveFlightLogsTitle=Czy chcesz USUNĄĆ wygenerowane pliki dziennika lotu (*.txt, *.json)?%n%nObejmuje to wszystkie pliki *.txt i *.json w:%n  <folder gry IL-2>\data\FlightLogs%n%nTe pliki zostały utworzone przez tracker i są regenerowane przy następnym uruchomieniu.%n%nKliknij TAK, aby usunąć pliki dziennika lotu.%nKliknij NIE, aby je zachować.
polish.IL2PageTitle=Wybierz folder instalacji IL-2 Great Battles
polish.IL2PageDescription=Wybierz folder, w którym zainstalowano IL-2 Great Battles.
polish.IL2PagePrompt=Proszę wybrać główny katalog instalacji IL-2 Great Battles.
polish.AdditionalIcons=Dodatkowe ikony:
polish.CreateDesktopIcon=Utwórz ikonę na &pulpicie
polish.GermanAwardsGroupDesc=Styl niemieckich odznaczeń:
polish.GermanAwards1957=Wersja 1957 (era Bundeswehry, domyślne)
polish.GermanAwardsWW2=Oryginalne niemieckie odznaczenia z II wojny światowej

; ============================================================================
; RUSSIAN
; ============================================================================
russian.SelectIL2Folder=Пожалуйста, выберите существующую папку установки IL-2 Great Battles.
russian.InvalidIL2Folder=Выбранная папка не является корректной установкой IL-2 Great Battles.%nПожалуйста, выберите правильный каталог установки игры.
russian.RemoveConfigTitle=Хотите УДАЛИТЬ файлы конфигурации (*.yaml)?%n%nЭто включает ваши настройки масштабирования званий и конфигурации наград.%n%nНажмите ДА, чтобы удалить файлы конфигурации.%nНажмите НЕТ, чтобы сохранить их.
russian.RemoveBackupTitle=Хотите УДАЛИТЬ файлы резервных копий?%n%nЭто включает:%n  - campaignsstates_*.backup%n  - campaign_popups_seen_*.backup%n  - campaignsstates_hash_index.json%n%nОни позволяют восстановить предыдущие состояния кампаний при переустановке.%n%nНажмите ДА, чтобы удалить файлы резервных копий.%nНажмите НЕТ, чтобы сохранить их.
russian.RemoveServiceRecordTitle=Хотите УДАЛИТЬ данные Campaign Service Record?%n%nЭто включает:%n  - Фотографии пилотов%n  - Личную информацию (имя, дата рождения, место рождения)%n  - Главы AI-историй%n%nРасположение: %%LOCALAPPDATA%%\.il2_campaign_service_record%n%nНажмите ДА, чтобы удалить данные Service Record.%nНажмите НЕТ, чтобы сохранить их.
russian.RemoveFlightLogsTitle=Хотите УДАЛИТЬ созданные файлы журнала полётов (*.txt, *.json)?%n%nЭто включает все файлы *.txt и *.json в:%n  <папка игры IL-2>\data\FlightLogs%n%nЭти файлы были созданы трекером и будут созданы заново при следующем запуске.%n%nНажмите ДА, чтобы удалить файлы журнала полётов.%nНажмите НЕТ, чтобы сохранить их.
russian.IL2PageTitle=Выберите папку установки IL-2 Great Battles
russian.IL2PageDescription=Выберите папку, где установлен IL-2 Great Battles.
russian.IL2PagePrompt=Пожалуйста, выберите основной каталог установки IL-2 Great Battles.
russian.AdditionalIcons=Дополнительные значки:
russian.CreateDesktopIcon=Создать значок на &рабочем столе
russian.GermanAwardsGroupDesc=Стиль немецких наград:
russian.GermanAwards1957=Версия 1957 г. (эпоха Бундесвера, по умолчанию)
russian.GermanAwardsWW2=Оригинальные немецкие награды эпохи Второй мировой войны

; ============================================================================
; CHINESE SIMPLIFIED
; ============================================================================
chinesesimplified.SelectIL2Folder=请选择现有的 IL-2 Great Battles 安装文件夹。
chinesesimplified.InvalidIL2Folder=所选文件夹似乎不是有效的 IL-2 Great Battles 安装。%n请选择正确的游戏安装目录。
chinesesimplified.RemoveConfigTitle=您要删除配置文件 (*.yaml) 吗？%n%n这包括您的自定义军衔缩放设置和勋章配置。%n%n点击"是"删除配置文件。%n点击"否"保留它们。
chinesesimplified.RemoveBackupTitle=您要删除备份文件吗？%n%n这包括：%n  - campaignsstates_*.backup%n  - campaign_popups_seen_*.backup%n  - campaignsstates_hash_index.json%n%n这些文件允许您在重新安装时恢复以前的战役状态。%n%n点击"是"删除备份文件。%n点击"否"保留它们。
chinesesimplified.RemoveServiceRecordTitle=您要删除 Campaign Service Record 数据吗？%n%n这包括：%n  - 飞行员照片%n  - 个人信息（姓名、生日、出生地）%n  - AI故事章节%n%n位置：%%LOCALAPPDATA%%\.il2_campaign_service_record%n%n点击"是"删除 Service Record 数据。%n点击"否"保留它们。
chinesesimplified.RemoveFlightLogsTitle=您要删除生成的飞行日志文件 (*.txt, *.json) 吗？%n%n这包括以下目录中的所有 *.txt 和 *.json 文件：%n  <IL-2 游戏目录>\data\FlightLogs%n%n这些文件由追踪器创建，下次运行时将重新生成。%n%n点击"是"删除飞行日志文件。%n点击"否"保留它们。
chinesesimplified.IL2PageTitle=选择 IL-2 Great Battles 安装文件夹
chinesesimplified.IL2PageDescription=选择 IL-2 Great Battles 的安装文件夹。
chinesesimplified.IL2PagePrompt=请选择 IL-2 Great Battles 的主安装目录。
chinesesimplified.AdditionalIcons=附加图标：
chinesesimplified.CreateDesktopIcon=创建桌面图标(&D)
chinesesimplified.GermanAwardsGroupDesc=德国勋章风格：
chinesesimplified.GermanAwards1957=1957年版本（联邦国防军时代，默认）
chinesesimplified.GermanAwardsWW2=二战时期原版德国勋章

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "awards_1957"; Description: "{cm:GermanAwards1957}"; GroupDescription: "{cm:GermanAwardsGroupDesc}"; Flags: exclusive
Name: "awards_ww2"; Description: "{cm:GermanAwardsWW2}"; GroupDescription: "{cm:GermanAwardsGroupDesc}"; Flags: exclusive unchecked

[Files]
; --- Tracker install folder ({app}) ---
; Font file for PDF export
Source: "IBMPlexSans-Light.ttf"; DestDir: "{app}"; Flags: ignoreversion
Source: "NotoSansSC-VF.ttf"; DestDir: "{app}"; Flags: ignoreversion

; Configuration files: only install if not already present (preserves user settings)
Source: "campaign_progress_config.yaml"; DestDir: "{app}"; Flags: onlyifdoesntexist uninsneveruninstall
Source: "object_categories.yaml"; DestDir: "{app}"; Flags: onlyifdoesntexist uninsneveruninstall
Source: "stock_campaigns.yaml"; DestDir: "{app}"; Flags: onlyifdoesntexist uninsneveruninstall

; Program files: always overwrite
Source: "IL2_CampaignTracker_v2.2_ML.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "IL2_Tracker_Control_GUI.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "mlg2txt.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "unGTP-IL2.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "QUICK_START.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "README.html"; DestDir: "{app}"; Flags: ignoreversion
Source: "README de.html"; DestDir: "{app}"; Flags: ignoreversion
Source: "README es.html"; DestDir: "{app}"; Flags: ignoreversion
Source: "README fr.html"; DestDir: "{app}"; Flags: ignoreversion
Source: "README ru.html"; DestDir: "{app}"; Flags: ignoreversion
Source: "README pl.html"; DestDir: "{app}"; Flags: ignoreversion
Source: "README zh-Hans.html"; DestDir: "{app}"; Flags: ignoreversion

; i18n translation files
Source: "locales\*.json"; DestDir: "{app}\locales"; Flags: ignoreversion

; --- Campaign Service Record ---
Source: "Campaign_Service_Record.exe"; DestDir: "{app}"; Flags: ignoreversion

; --- Career Service Record ---
Source: "Career_Service_Record.exe"; DestDir: "{app}"; Flags: ignoreversion

; --- Shared internal bundle (covers both Service Record builds) ---
Source: "_internal\*"; DestDir: "{app}\_internal"; Flags: recursesubdirs createallsubdirs ignoreversion
Source: "IL-2_Tracker_award_coordinates.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "IL-2_Tracker_career_award_coordinates.json"; DestDir: "{app}"; Flags: ignoreversion

; --- Setting Manager ---
Source: "IL2_Settings_Manager.exe"; DestDir: "{app}"; Flags: ignoreversion

; --- Cleanup utility for uninstaller ---
Source: "cleanup_tracker_content.exe"; DestDir: "{app}"; Flags: ignoreversion

; --- squadrons.json: Career Service Record internal lookup table ---
; Must live next to the EXE so data_dir/CampaignRanksAwards/squadrons.json resolves correctly.
; It is NOT copied into IL-2 (IL-2 does not use it).
Source: "CampaignRanksAwards\squadrons.json"; DestDir: "{app}"; Flags: ignoreversion

; --- Copy characterbio into IL-2 ---
; This places the career pilot biography texts into: <IL-2>\data\swf\il2\characterbio\*
Source: "characterbio\*"; DestDir: "{code:GetIL2Dir}\data\swf\il2\characterbio"; Flags: recursesubdirs createallsubdirs ignoreversion

; --- Copy CampaignRanksAwards into IL-2 ---
; This places content into: <IL-2>\data\swf\CampaignRanksAwards\*
; Both Germany variants are always installed so the user can switch later.
; The Germany subfolder is handled separately below (WW2 vs 1957 toggle).
; squadrons.json is excluded — it is tracker-internal and not needed by IL-2.
Source: "CampaignRanksAwards\*"; DestDir: "{code:GetIL2Dir}\data\swf\CampaignRanksAwards"; Flags: recursesubdirs createallsubdirs ignoreversion; Excludes: "Germany\*,Germany - WW2\*,squadrons.json,squadrons\*"

; --- 1957 chosen (default) ---
; Active:    Germany (1957) -> Germany
; Alternate: Germany - WW2  -> Germany - WW2
Source: "CampaignRanksAwards\Germany\*";       DestDir: "{code:GetIL2Dir}\data\swf\CampaignRanksAwards\Germany";       Flags: recursesubdirs createallsubdirs ignoreversion; Tasks: awards_1957
Source: "CampaignRanksAwards\Germany - WW2\*"; DestDir: "{code:GetIL2Dir}\data\swf\CampaignRanksAwards\Germany - WW2"; Flags: recursesubdirs createallsubdirs ignoreversion; Tasks: awards_1957

; --- WW2 chosen ---
; Active:    Germany - WW2  -> Germany
; Alternate: Germany (1957) -> Germany - 1957
Source: "CampaignRanksAwards\Germany - WW2\*"; DestDir: "{code:GetIL2Dir}\data\swf\CampaignRanksAwards\Germany";       Flags: recursesubdirs createallsubdirs ignoreversion; Tasks: awards_ww2
Source: "CampaignRanksAwards\Germany\*";       DestDir: "{code:GetIL2Dir}\data\swf\CampaignRanksAwards\Germany - 1957"; Flags: recursesubdirs createallsubdirs ignoreversion; Tasks: awards_ww2

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon
Name: "{group}\Uninstall IL-2 Campaign Tracker"; Filename: "{uninstallexe}"


[Registry]
; Store IL-2 install path for uninstall cleanup
Root: HKLM; Subkey: "Software\{#MyAppName}"; ValueType: string; ValueName: "IL2Path"; ValueData: "{code:GetIL2Dir}"; Flags: uninsdeletekey

[Code]

var
  IL2DirPage: TInputDirWizardPage;
  IL2DirValue: string;
  
  { Uninstall options }
  RemoveConfigFiles: Boolean;
  RemoveBackupFiles: Boolean;
  RemoveServiceRecordData: Boolean;
  RemoveFlightLogs: Boolean;

{ ----------------------------
  Helpers
  ---------------------------- }

function NormalizeDir(const S: string): string;
begin
  Result := Trim(S);
  while (Length(Result) > 0) and (Result[Length(Result)] = '\') do
    Delete(Result, Length(Result), 1);
end;

function FindLocaleValueRange(const S: string; var StartIdx, EndIdx: Integer): Boolean;
var
  KeyPos, ColonPos, QuoteStart, QuoteEnd, I: Integer;
begin
  Result := False;
  StartIdx := 0;
  EndIdx := 0;

  KeyPos := Pos('"locale"', S);
  if KeyPos = 0 then
    Exit;

  ColonPos := 0;
  for I := KeyPos + Length('"locale"') to Length(S) do
    if S[I] = ':' then
    begin
      ColonPos := I;
      Break;
    end;
  if ColonPos = 0 then
    Exit;

  QuoteStart := 0;
  for I := ColonPos + 1 to Length(S) do
    if S[I] = '"' then
    begin
      QuoteStart := I;
      Break;
    end;
  if QuoteStart = 0 then
    Exit;

  QuoteEnd := 0;
  for I := QuoteStart + 1 to Length(S) do
    if S[I] = '"' then
    begin
      QuoteEnd := I;
      Break;
    end;
  if QuoteEnd = 0 then
    Exit;

  StartIdx := QuoteStart + 1;
  EndIdx := QuoteEnd - 1;
  if EndIdx < StartIdx then
    Exit;

  Result := True;
end;

function ReadLocaleSettingJson(const FilePath: string): string;
var
  Content: AnsiString;
  Raw: string;
  StartIdx, EndIdx: Integer;
begin
  Result := '';
  if not FileExists(FilePath) then
    Exit;

  if LoadStringFromFile(FilePath, Content) then
  begin
    Raw := String(Content);
    if FindLocaleValueRange(Raw, StartIdx, EndIdx) then
      Result := Trim(Copy(Raw, StartIdx, EndIdx - StartIdx + 1));
  end;
end;

function UpdateLocaleSettingJson(const FilePath, LocaleValue: string): Boolean;
var
  Content: AnsiString;
  Raw: string;
  StartIdx, EndIdx: Integer;
  NewContent: string;
begin
  Result := False;

  if FileExists(FilePath) and LoadStringFromFile(FilePath, Content) then
  begin
    Raw := String(Content);
    if FindLocaleValueRange(Raw, StartIdx, EndIdx) then
    begin
      NewContent := Copy(Raw, 1, StartIdx - 1) + LocaleValue + Copy(Raw, EndIdx + 1, Length(Raw) - EndIdx);
      Result := SaveStringToFile(FilePath, NewContent, False);
      Exit;
    end;
  end;

  NewContent := '{'#13#10 + '  "locale": "' + LocaleValue + '"'#13#10 + '}';
  Result := SaveStringToFile(FilePath, NewContent, False);
end;

function LooksLikeIL2Root(const Dir: string): Boolean;
begin
  { Keep this check internal (do not mention it in UI text).
    Adjust markers if needed. These are safe and lightweight. }
  Result :=
    DirExists(Dir + '\data') and
    DirExists(Dir + '\data\swf');
end;

function GetStoredIL2Path(): string;
begin
  Result := '';

  { Prefer 64-bit HKLM view (recommended write target) }
  if not RegQueryStringValue(HKLM64, 'Software\{#MyAppName}', 'IL2Path', Result) then
  begin
    { Fallback: 32-bit view (WOW6432Node) for legacy installs }
    RegQueryStringValue(HKLM32, 'Software\{#MyAppName}', 'IL2Path', Result);
  end;
end;

function GetIL2Dir(Param: string): string;
begin
  // Used by [Files]/[Registry] as {code:GetIL2Dir} 
  Result := IL2DirValue;

  { Fallback (e.g., edge cases) }
  if Result = '' then
    Result := GetStoredIL2Path();
end;

procedure PrefillIL2Dir;
var
  Prev: string;
  DefaultSteamIL2: string;
begin
  Prev := NormalizeDir(GetStoredIL2Path());
  DefaultSteamIL2 :=
    'C:\Program Files (x86)\Steam\steamapps\common\IL-2 Sturmovik Battle of Stalingrad';

  if (Prev <> '') and DirExists(Prev) then
    IL2DirPage.Values[0] := Prev
  else if DirExists(DefaultSteamIL2) then
    IL2DirPage.Values[0] := DefaultSteamIL2
  else
    IL2DirPage.Values[0] := 'C:\Program Files (x86)\Steam\steamapps\common';
end;

{ ----------------------------
  Wizard setup
  ---------------------------- }

procedure InitializeWizard;
begin
  IL2DirPage := CreateInputDirPage(
    wpSelectDir,
    CustomMessage('IL2PageTitle'),
    CustomMessage('IL2PageDescription'),
    CustomMessage('IL2PagePrompt'),
    False,
    ''
  );

  // Create the first (and only) directory input row
  IL2DirPage.Add('');

  PrefillIL2Dir();
end;

function GetInstallerLocaleCode(): string;
begin
  if ActiveLanguage = 'german' then
    Result := 'de'
  else if ActiveLanguage = 'french' then
    Result := 'fr'
  else if ActiveLanguage = 'spanish' then
    Result := 'es'
  else if ActiveLanguage = 'polish' then
    Result := 'pl'
  else if ActiveLanguage = 'russian' then
    Result := 'ru'
  else if ActiveLanguage = 'chinesesimplified' then
    Result := 'zh'
  else
    Result := 'en';
end;

procedure WriteLocaleOverrideFile();
var
  LocaleFile: string;
  LocaleValue: string;
begin
  LocaleValue := GetInstallerLocaleCode();
  LocaleFile := ExpandConstant('{app}\campaign_tracker_settings.json');
  if LocaleValue <> '' then
    UpdateLocaleSettingJson(LocaleFile, LocaleValue);
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssPostInstall then
    WriteLocaleOverrideFile();
end;

function ReadAppLocale(): string;
var
  LocaleFile: string;
  LocaleValue: string;
begin
  Result := 'en';
  LocaleFile := ExpandConstant('{app}\campaign_tracker_settings.json');
  LocaleValue := ReadLocaleSettingJson(LocaleFile);
  if LocaleValue <> '' then
    Result := LocaleValue;
end;

function GetUninstallMessage(const Key: string; const LocaleValue: string): string;
begin
  Result := '';

  if LocaleValue = 'de' then
  begin
    if Key = 'RemoveConfigTitle' then
      Result := 'Möchten Sie Ihre Konfigurationsdateien (*.yaml) ENTFERNEN?'#13#10#13#10 +
                'Dies umfasst Ihre benutzerdefinierten Rang-Skalierungseinstellungen und Auszeichnungskonfigurationen.'#13#10#13#10 +
                'Klicken Sie JA, um die Konfigurationsdateien zu entfernen.'#13#10 +
                'Klicken Sie NEIN, um sie zu behalten.'
    else if Key = 'RemoveBackupTitle' then
      Result := 'Möchten Sie Ihre Backup-Dateien ENTFERNEN?'#13#10#13#10 +
                'Dies umfasst:'#13#10 +
                '  - campaignsstates_*.backup'#13#10 +
                '  - campaign_popups_seen_*.backup'#13#10 +
                '  - campaignsstates_hash_index.json'#13#10#13#10 +
                'Diese ermöglichen die Wiederherstellung früherer Kampagnenstände bei einer Neuinstallation.'#13#10#13#10 +
                'Klicken Sie JA, um die Backup-Dateien zu entfernen.'#13#10 +
                'Klicken Sie NEIN, um sie zu behalten.'
    else if Key = 'RemoveServiceRecordTitle' then
      Result := 'Möchten Sie Ihre Campaign Service Record Daten ENTFERNEN?'#13#10#13#10 +
                'Dies umfasst:'#13#10 +
                '  - Pilotenfotos'#13#10 +
                '  - Persönliche Informationen (Name, Geburtstag, Geburtsort)'#13#10 +
                '  - KI-Story-Kapitel'#13#10#13#10 +
                'Speicherort: %LOCALAPPDATA%\.il2_campaign_service_record'#13#10#13#10 +
                'Klicken Sie JA, um die Service Record Daten zu entfernen.'#13#10 +
                'Klicken Sie NEIN, um sie zu behalten.'
    else if Key = 'RemoveFlightLogsTitle' then
      Result := 'Möchten Sie die generierten Flugprotokoll-Dateien ENTFERNEN (*.txt, *.json)?'#13#10#13#10 +
                'Dies umfasst alle *.txt und *.json Dateien in:'#13#10 +
                '  <IL-2 Spielordner>\data\FlightLogs'#13#10#13#10 +
                'Diese Dateien wurden vom Tracker erstellt und werden beim nächsten Start neu generiert.'#13#10#13#10 +
                'Klicken Sie JA, um die Flugprotokoll-Dateien zu entfernen.'#13#10 +
                'Klicken Sie NEIN, um sie zu behalten.';
  end
  else if LocaleValue = 'fr' then
  begin
    if Key = 'RemoveConfigTitle' then
      Result := 'Voulez-vous SUPPRIMER vos fichiers de configuration (*.yaml) ?'#13#10#13#10 +
                'Cela inclut vos paramètres de progression de rang et configurations de décorations.'#13#10#13#10 +
                'Cliquez OUI pour supprimer les fichiers de configuration.'#13#10 +
                'Cliquez NON pour les conserver.'
    else if Key = 'RemoveBackupTitle' then
      Result := 'Voulez-vous SUPPRIMER vos fichiers de sauvegarde ?'#13#10#13#10 +
                'Cela inclut :'#13#10 +
                '  - campaignsstates_*.backup'#13#10 +
                '  - campaign_popups_seen_*.backup'#13#10 +
                '  - campaignsstates_hash_index.json'#13#10#13#10 +
                'Ceux-ci permettent de restaurer les états de campagne précédents si vous réinstallez.'#13#10#13#10 +
                'Cliquez OUI pour supprimer les fichiers de sauvegarde.'#13#10 +
                'Cliquez NON pour les conserver.'
    else if Key = 'RemoveServiceRecordTitle' then
      Result := 'Voulez-vous SUPPRIMER vos données Campaign Service Record ?'#13#10#13#10 +
                'Cela inclut :'#13#10 +
                '  - Photos de pilote'#13#10 +
                '  - Informations personnelles (nom, date de naissance, lieu de naissance)'#13#10 +
                '  - Chapitres d''histoires IA'#13#10#13#10 +
                'Emplacement : %LOCALAPPDATA%\.il2_campaign_service_record'#13#10#13#10 +
                'Cliquez OUI pour supprimer les données Service Record.'#13#10 +
                'Cliquez NON pour les conserver.'
    else if Key = 'RemoveFlightLogsTitle' then
      Result := 'Voulez-vous SUPPRIMER les fichiers de journal de vol générés (*.txt, *.json) ?'#13#10#13#10 +
                'Cela inclut tous les fichiers *.txt et *.json dans :'#13#10 +
                '  <dossier du jeu IL-2>\data\FlightLogs'#13#10#13#10 +
                'Ces fichiers ont été créés par le tracker et sont régénérés au prochain démarrage.'#13#10#13#10 +
                'Cliquez OUI pour supprimer les fichiers de journal de vol.'#13#10 +
                'Cliquez NON pour les conserver.';
  end
  else if LocaleValue = 'es' then
  begin
    if Key = 'RemoveConfigTitle' then
      Result := '¿Desea ELIMINAR sus archivos de configuración (*.yaml)?'#13#10#13#10 +
                'Esto incluye sus ajustes de escalado de rangos y configuraciones de condecoraciones.'#13#10#13#10 +
                'Haga clic en SÍ para eliminar los archivos de configuración.'#13#10 +
                'Haga clic en NO para conservarlos.'
    else if Key = 'RemoveBackupTitle' then
      Result := '¿Desea ELIMINAR sus archivos de respaldo?'#13#10#13#10 +
                'Esto incluye:'#13#10 +
                '  - campaignsstates_*.backup'#13#10 +
                '  - campaign_popups_seen_*.backup'#13#10 +
                '  - campaignsstates_hash_index.json'#13#10#13#10 +
                'Estos permiten restaurar estados de campaña anteriores si reinstala.'#13#10#13#10 +
                'Haga clic en SÍ para eliminar los archivos de respaldo.'#13#10 +
                'Haga clic en NO para conservarlos.'
    else if Key = 'RemoveServiceRecordTitle' then
      Result := '¿Desea ELIMINAR sus datos de Campaign Service Record?'#13#10#13#10 +
                'Esto incluye:'#13#10 +
                '  - Fotos de piloto'#13#10 +
                '  - Información personal (nombre, fecha de nacimiento, lugar de nacimiento)'#13#10 +
                '  - Capítulos de historias IA'#13#10#13#10 +
                'Ubicación: %LOCALAPPDATA%\.il2_campaign_service_record'#13#10#13#10 +
                'Haga clic en SÍ para eliminar los datos de Service Record.'#13#10 +
                'Haga clic en NO para conservarlos.'
    else if Key = 'RemoveFlightLogsTitle' then
      Result := '¿Desea ELIMINAR los archivos de registro de vuelo generados (*.txt, *.json)?'#13#10#13#10 +
                'Esto incluye todos los archivos *.txt y *.json en:'#13#10 +
                '  <carpeta del juego IL-2>\data\FlightLogs'#13#10#13#10 +
                'Estos archivos fueron creados por el tracker y se regeneran en el próximo inicio.'#13#10#13#10 +
                'Haga clic en SÍ para eliminar los archivos de registro de vuelo.'#13#10 +
                'Haga clic en NO para conservarlos.';
  end
  else if LocaleValue = 'pl' then
  begin
    if Key = 'RemoveConfigTitle' then
      Result := 'Czy chcesz USUNĄĆ pliki konfiguracyjne (*.yaml)?'#13#10#13#10 +
                'Obejmuje to niestandardowe ustawienia skalowania rang i konfiguracje odznaczeń.'#13#10#13#10 +
                'Kliknij TAK, aby usunąć pliki konfiguracyjne.'#13#10 +
                'Kliknij NIE, aby je zachować.'
    else if Key = 'RemoveBackupTitle' then
      Result := 'Czy chcesz USUNĄĆ pliki kopii zapasowych?'#13#10#13#10 +
                'Obejmuje to:'#13#10 +
                '  - campaignsstates_*.backup'#13#10 +
                '  - campaign_popups_seen_*.backup'#13#10 +
                '  - campaignsstates_hash_index.json'#13#10#13#10 +
                'Pozwalają one przywrócić poprzednie stany kampanii po ponownej instalacji.'#13#10#13#10 +
                'Kliknij TAK, aby usunąć pliki kopii zapasowych.'#13#10 +
                'Kliknij NIE, aby je zachować.'
    else if Key = 'RemoveServiceRecordTitle' then
      Result := 'Czy chcesz USUNĄĆ dane Campaign Service Record?'#13#10#13#10 +
                'Obejmuje to:'#13#10 +
                '  - Zdjęcia pilotów'#13#10 +
                '  - Dane osobowe (imię, data urodzenia, miejsce urodzenia)'#13#10 +
                '  - Rozdziały historii AI'#13#10#13#10 +
                'Lokalizacja: %LOCALAPPDATA%\.il2_campaign_service_record'#13#10#13#10 +
                'Kliknij TAK, aby usunąć dane Service Record.'#13#10 +
                'Kliknij NIE, aby je zachować.'
    else if Key = 'RemoveFlightLogsTitle' then
      Result := 'Czy chcesz USUNĄĆ wygenerowane pliki dziennika lotu (*.txt, *.json)?'#13#10#13#10 +
                'Obejmuje to wszystkie pliki *.txt i *.json w:'#13#10 +
                '  <folder gry IL-2>\data\FlightLogs'#13#10#13#10 +
                'Te pliki zostały utworzone przez tracker i są regenerowane przy następnym uruchomieniu.'#13#10#13#10 +
                'Kliknij TAK, aby usunąć pliki dziennika lotu.'#13#10 +
                'Kliknij NIE, aby je zachować.';
  end
  else if LocaleValue = 'ru' then
  begin
    if Key = 'RemoveConfigTitle' then
      Result := 'Хотите УДАЛИТЬ файлы конфигурации (*.yaml)?'#13#10#13#10 +
                'Это включает ваши настройки масштабирования званий и конфигурации наград.'#13#10#13#10 +
                'Нажмите ДА, чтобы удалить файлы конфигурации.'#13#10 +
                'Нажмите НЕТ, чтобы сохранить их.'
    else if Key = 'RemoveBackupTitle' then
      Result := 'Хотите УДАЛИТЬ файлы резервных копий?'#13#10#13#10 +
                'Это включает:'#13#10 +
                '  - campaignsstates_*.backup'#13#10 +
                '  - campaign_popups_seen_*.backup'#13#10 +
                '  - campaignsstates_hash_index.json'#13#10#13#10 +
                'Они позволяют восстановить предыдущие состояния кампаний при переустановке.'#13#10#13#10 +
                'Нажмите ДА, чтобы удалить файлы резервных копий.'#13#10 +
                'Нажмите НЕТ, чтобы сохранить их.'
    else if Key = 'RemoveServiceRecordTitle' then
      Result := 'Хотите УДАЛИТЬ данные Campaign Service Record?'#13#10#13#10 +
                'Это включает:'#13#10 +
                '  - Фотографии пилотов'#13#10 +
                '  - Личную информацию (имя, дата рождения, место рождения)'#13#10 +
                '  - Главы AI-историй'#13#10#13#10 +
                'Расположение: %LOCALAPPDATA%\.il2_campaign_service_record'#13#10#13#10 +
                'Нажмите ДА, чтобы удалить данные Service Record.'#13#10 +
                'Нажмите НЕТ, чтобы сохранить их.'
    else if Key = 'RemoveFlightLogsTitle' then
      Result := 'Хотите УДАЛИТЬ созданные файлы журнала полётов (*.txt, *.json)?'#13#10#13#10 +
                'Это включает все файлы *.txt и *.json в:'#13#10 +
                '  <папка игры IL-2>\data\FlightLogs'#13#10#13#10 +
                'Эти файлы были созданы трекером и будут созданы заново при следующем запуске.'#13#10#13#10 +
                'Нажмите ДА, чтобы удалить файлы журнала полётов.'#13#10 +
                'Нажмите НЕТ, чтобы сохранить их.';
  end
  else if LocaleValue = 'zh' then
  begin
    if Key = 'RemoveConfigTitle' then
      Result := '您要删除配置文件 (*.yaml) 吗？'#13#10#13#10 +
                '这包括您的自定义军衔缩放设置和勋章配置。'#13#10#13#10 +
                '点击"是"删除配置文件。'#13#10 +
                '点击"否"保留它们。'
    else if Key = 'RemoveBackupTitle' then
      Result := '您要删除备份文件吗？'#13#10#13#10 +
                '这包括：'#13#10 +
                '  - campaignsstates_*.backup'#13#10 +
                '  - campaign_popups_seen_*.backup'#13#10 +
                '  - campaignsstates_hash_index.json'#13#10#13#10 +
                '这些文件允许您在重新安装时恢复以前的战役状态。'#13#10#13#10 +
                '点击"是"删除备份文件。'#13#10 +
                '点击"否"保留它们。'
    else if Key = 'RemoveServiceRecordTitle' then
      Result := '您要删除 Campaign Service Record 数据吗？'#13#10#13#10 +
                '这包括：'#13#10 +
                '  - 飞行员照片'#13#10 +
                '  - 个人信息（姓名、生日、出生地）'#13#10 +
                '  - AI故事章节'#13#10#13#10 +
                '位置：%LOCALAPPDATA%\.il2_campaign_service_record'#13#10#13#10 +
                '点击"是"删除 Service Record 数据。'#13#10 +
                '点击"否"保留它们。'
    else if Key = 'RemoveFlightLogsTitle' then
      Result := '您要删除生成的飞行日志文件 (*.txt, *.json) 吗？'#13#10#13#10 +
                '这包括以下目录中的所有 *.txt 和 *.json 文件：'#13#10 +
                '  <IL-2 游戏目录>\data\FlightLogs'#13#10#13#10 +
                '这些文件由追踪器创建，下次运行时将重新生成。'#13#10#13#10 +
                '点击"是"删除飞行日志文件。'#13#10 +
                '点击"否"保留它们。';
  end
  else
  begin
    if Key = 'RemoveConfigTitle' then
      Result := 'Do you want to REMOVE your configuration files (*.yaml)?'#13#10#13#10 +
                'This includes your custom rank scaling settings and award configurations.'#13#10#13#10 +
                'Click YES to remove configuration files.'#13#10 +
                'Click NO to keep them.'
    else if Key = 'RemoveBackupTitle' then
      Result := 'Do you want to REMOVE your backup files?'#13#10#13#10 +
                'This includes:'#13#10 +
                '  - campaignsstates_*.backup'#13#10 +
                '  - campaign_popups_seen_*.backup'#13#10 +
                '  - campaignsstates_hash_index.json'#13#10#13#10 +
                'These allow you to restore previous campaign states if you reinstall.'#13#10#13#10 +
                'Click YES to remove backup files.'#13#10 +
                'Click NO to keep them.'
    else if Key = 'RemoveServiceRecordTitle' then
      Result := 'Do you want to REMOVE your Campaign Service Record data?'#13#10#13#10 +
                'This includes:'#13#10 +
                '  - Pilot photos'#13#10 +
                '  - Personal information (name, birthday, birthplace)'#13#10 +
                '  - AI story chapters'#13#10#13#10 +
                'Location: %LOCALAPPDATA%\.il2_campaign_service_record'#13#10#13#10 +
                'Click YES to remove Service Record data.'#13#10 +
                'Click NO to keep it.'
    else if Key = 'RemoveFlightLogsTitle' then
      Result := 'Do you want to REMOVE the generated flight log files (*.txt, *.json)?'#13#10#13#10 +
                'This includes all *.txt and *.json files in:'#13#10 +
                '  <IL-2 game folder>\data\FlightLogs'#13#10#13#10 +
                'These files were created by the tracker and are regenerated on the next run.'#13#10#13#10 +
                'Click YES to remove flight log files.'#13#10 +
                'Click NO to keep them.';
  end;
end;


function NextButtonClick(CurPageID: Integer): Boolean;
var
  D: string;
begin
  Result := True;

  if CurPageID = IL2DirPage.ID then
  begin
    D := NormalizeDir(IL2DirPage.Values[0]);

    if (D = '') or (not DirExists(D)) then
    begin
      MsgBox(CustomMessage('SelectIL2Folder'), mbError, MB_OK);
      Result := False;
      Exit;
    end;

    if not LooksLikeIL2Root(D) then
    begin
      MsgBox(CustomMessage('InvalidIL2Folder'), mbError, MB_OK);
      Result := False;
      Exit;
    end;

    { Store for this run }
    IL2DirValue := D;
  end;
end;

{ ----------------------------
  Uninstall: Ask user about keeping files
  ---------------------------- }

function InitializeUninstall(): Boolean;
var
  MsgResult: Integer;
  AppLocale: string;
begin
  Result := True;
  AppLocale := ReadAppLocale();
  
  { Default: keep all user-generated files }
  RemoveConfigFiles := False;
  RemoveBackupFiles := False;
  RemoveServiceRecordData := False;
  RemoveFlightLogs := False;

  { Ask about configuration files }
  MsgResult := MsgBox(GetUninstallMessage('RemoveConfigTitle', AppLocale), mbConfirmation, MB_YESNO);
  RemoveConfigFiles := (MsgResult = IDYES);

  { Ask about backup files }
  MsgResult := MsgBox(GetUninstallMessage('RemoveBackupTitle', AppLocale), mbConfirmation, MB_YESNO);
  RemoveBackupFiles := (MsgResult = IDYES);

  { Ask about Campaign Service Record data }
  MsgResult := MsgBox(GetUninstallMessage('RemoveServiceRecordTitle', AppLocale), mbConfirmation, MB_YESNO);
  RemoveServiceRecordData := (MsgResult = IDYES);

  { Ask about generated flight log files in <IL-2>\data\FlightLogs }
  MsgResult := MsgBox(GetUninstallMessage('RemoveFlightLogsTitle', AppLocale), mbConfirmation, MB_YESNO);
  RemoveFlightLogs := (MsgResult = IDYES);
end;

// ----------------------------
//  Uninstall cleanup
//  - Runs cleanup_tracker_content.exe to remove Events/Debriefings from info.locale files
//  - Optionally deletes:
//    1) Configuration files (*.yaml) in {app}
//    2) <IL-2>\data\swf\CampaignRanksAwards\*
//    3) For each UUID folder:
//       <IL-2>\data\swf\il2\usersave\{UUID}\campaign\
//         - campaignsstates_*.backup
//         - campaign_popups_seen_*.backup
//         - campaignsstates_hash_index.json
//    4) Generated flight log files:
//       <IL-2>\data\FlightLogs\*.txt
//       <IL-2>\data\FlightLogs\*.json
//    5) Campaign Service Record data:
//       %LOCALAPPDATA%\.il2_campaign_service_record\
//         - pilot_photos\
//         - campaign_personal_data.json
//         - story_data\careers\ and story_data\campaigns\ (AI story chapters)
//  ----------------------------

procedure DeleteUserSaveCampaignFiles(const IL2Root: string);
var
  UsersaveRoot, SearchPath, UUIDDir, CampaignDir: string;
  FindRec: TFindRec;
begin
  if not RemoveBackupFiles then
  begin
    { User wants to keep backups - skip this step }
    Exit;
  end;

  UsersaveRoot := IL2Root + '\data\swf\il2\usersave';
  if not DirExists(UsersaveRoot) then
    Exit;

  SearchPath := UsersaveRoot + '\*';
  if FindFirst(SearchPath, FindRec) then
  try
    repeat
      if (FindRec.Attributes and FILE_ATTRIBUTE_DIRECTORY) <> 0 then
      begin
        if (FindRec.Name <> '.') and (FindRec.Name <> '..') then
        begin
          UUIDDir := UsersaveRoot + '\' + FindRec.Name;
          CampaignDir := UUIDDir + '\campaign';

          if DirExists(CampaignDir) then
          begin
            { Wildcard deletes – ignore errors }
            DelTree(CampaignDir + '\campaignsstates_*.backup', False, True, False);
            DelTree(CampaignDir + '\campaign_popups_seen_*.backup', False, True, False);

            { Single file }
            DeleteFile(CampaignDir + '\campaignsstates_hash_index.json');
          end;
        end;
      end;
    until not FindNext(FindRec);
  finally
    FindClose(FindRec);
  end;
end;

procedure DeleteServiceRecordData();
var
  ServiceRecordDir: string;
begin
  if not RemoveServiceRecordData then
  begin
    { User wants to keep Service Record data - skip this step }
    Exit;
  end;

  { Get %LOCALAPPDATA%\.il2_campaign_service_record }
  ServiceRecordDir := ExpandConstant('{localappdata}\.il2_campaign_service_record');
  
  if DirExists(ServiceRecordDir) then
  begin
    { Delete entire directory including:
      - pilot_photos/
      - campaign_personal_data.json
      - story_data/careers/
      - story_data/campaigns/ }
    DelTree(ServiceRecordDir, True, True, True);
  end;
end;

procedure RestoreCampaignInfoBackups(const IL2Root: string);
var
  CampaignsDir, CampaignDir: string;
  FindRecCampaign, FindRecFile: TFindRec;
  BackupFile, OriginalFile: string;
  HasBackups: Boolean;
begin
  { <IL-2>\data\Campaigns }
  CampaignsDir := AddBackslash(IL2Root) + 'data\Campaigns';
  
  if not DirExists(CampaignsDir) then
    Exit;

  { Iterate through each campaign folder }
  if FindFirst(CampaignsDir + '\*', FindRecCampaign) then
  try
    repeat
      if (FindRecCampaign.Attributes and FILE_ATTRIBUTE_DIRECTORY) <> 0 then
      begin
        if (FindRecCampaign.Name <> '.') and (FindRecCampaign.Name <> '..') and (FindRecCampaign.Name <> 'usersave') then
        begin
          CampaignDir := CampaignsDir + '\' + FindRecCampaign.Name;
          HasBackups := False;

          { Check if this campaign has any .backup files }
          if FindFirst(CampaignDir + '\*.backup', FindRecFile) then
          try
            HasBackups := True;
          finally
            FindClose(FindRecFile);
          end;

          { Only process campaigns with backup files }
          if HasBackups then
          begin
            { Delete all info.locale=*.txt files (without .backup extension) }
            if FindFirst(CampaignDir + '\info.locale=*.txt', FindRecFile) then
            try
              repeat
                if (FindRecFile.Attributes and FILE_ATTRIBUTE_DIRECTORY) = 0 then
                begin
                  OriginalFile := CampaignDir + '\' + FindRecFile.Name;
                  { Only delete if it's NOT a backup file }
                  if Pos('.backup', LowerCase(OriginalFile)) = 0 then
                  begin
                    DeleteFile(OriginalFile);
                  end;
                end;
              until not FindNext(FindRecFile);
            finally
              FindClose(FindRecFile);
            end;

            { Rename all *.backup files to remove .backup extension }
            if FindFirst(CampaignDir + '\info.locale=*.txt.backup', FindRecFile) then
            try
              repeat
                if (FindRecFile.Attributes and FILE_ATTRIBUTE_DIRECTORY) = 0 then
                begin
                  BackupFile := CampaignDir + '\' + FindRecFile.Name;
                  OriginalFile := Copy(BackupFile, 1, Length(BackupFile) - Length('.backup'));
                  RenameFile(BackupFile, OriginalFile);
                end;
              until not FindNext(FindRecFile);
            finally
              FindClose(FindRecFile);
            end;
          end;
        end;
      end;
    until not FindNext(FindRecCampaign);
  finally
    FindClose(FindRecCampaign);
  end;
end;

procedure RunCleanupTrackerContent(const IL2Root: string);
var
  CleanupExe: string;
  ResultCode: Integer;
begin
  { Run cleanup_tracker_content.exe to remove Events/Debriefings from info.locale files }
  CleanupExe := ExpandConstant('{app}\cleanup_tracker_content.exe');
  
  if FileExists(CleanupExe) then
  begin
    { Run silently with --quiet flag }
    Exec(CleanupExe, '--uninstall --quiet --il2-path "' + IL2Root + '"', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
    { Ignore result code - cleanup is best-effort }
  end;
end;

procedure DeleteFlightLogFiles(const IL2Root: string);
var
  FlightLogsDir: string;
begin
  if not RemoveFlightLogs then
    Exit;

  FlightLogsDir := IL2Root + '\data\FlightLogs';
  if not DirExists(FlightLogsDir) then
    Exit;

  { Delete all tracker-generated *.txt and *.json files; leave *.mlg (game originals) untouched }
  DelTree(FlightLogsDir + '\*.txt', False, True, False);
  DelTree(FlightLogsDir + '\*.json', False, True, False);
end;

procedure DeleteAppFiles();
var
  AppDir: string;
  FindRec: TFindRec;
  FilePath, FileExt: string;
begin
  AppDir := ExpandConstant('{app}');
  
  if not DirExists(AppDir) then
    Exit;
    
  { Find and delete files based on extension }
  if FindFirst(AppDir + '\*', FindRec) then
  try
    repeat
      if (FindRec.Attributes and FILE_ATTRIBUTE_DIRECTORY) = 0 then
      begin
        FilePath := AppDir + '\' + FindRec.Name;
        FileExt := LowerCase(ExtractFileExt(FindRec.Name));
        
        { Keep *.yaml files unless user chose to remove config }
        if (not RemoveConfigFiles) and (FileExt = '.yaml') then
        begin
          { Keep this file }
        end
        else
        begin
          { Delete all other files: *.json, *.log, *.exe, *.txt, *.html, *.ttf, etc. }
          DeleteFile(FilePath);
        end;
      end;
    until not FindNext(FindRec);
  finally
    FindClose(FindRec);
  end;
  
  { Delete subdirectories }
  DelTree(AppDir + '\reports', True, True, True);
  DelTree(AppDir + '\_internal', True, True, True);
  DelTree(AppDir + '\locales', True, True, True);
  if RemoveFlightLogs then
    DelTree(AppDir + '\career', True, True, True);  { Career Service Record debrief cache — derived from flight logs, keep if logs are kept }
  
  { Try to remove the app directory if empty (will fail if config files kept) }
  RemoveDir(AppDir);
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
  IL2Root, AwardsDir: string;
begin
  if CurUninstallStep = usUninstall then
  begin
    IL2Root := NormalizeDir(GetStoredIL2Path());

    if (IL2Root <> '') and DirExists(IL2Root) then
    begin
      { Step 1: Remove tracker content from info.locale files }
      RunCleanupTrackerContent(IL2Root);
      
      { Step 2: Restore original info.locale files from .backup }
      { This restores original info.locale=*.txt files from .backup versions }
      RestoreCampaignInfoBackups(IL2Root);
    
      { Step 3: Remove CampaignRanksAwards folder }
      AwardsDir := IL2Root + '\data\swf\CampaignRanksAwards';
      if DirExists(AwardsDir) then
        DelTree(AwardsDir, True, True, True);

      { Step 3b: Remove characterbio folder }
      AwardsDir := IL2Root + '\data\swf\il2\characterbio';
      if DirExists(AwardsDir) then
        DelTree(AwardsDir, True, True, True);

      { Step 4: Remove tracker-related files from usersave UUID campaign folders }
      { (respects RemoveBackupFiles setting) }
      DeleteUserSaveCampaignFiles(IL2Root);

      { Step 5: Delete generated *.txt and *.json from FlightLogs }
      { (respects RemoveFlightLogs setting) }
      DeleteFlightLogFiles(IL2Root);
    end;

    { Step 6: Delete Campaign Service Record data }
    { (respects RemoveServiceRecordData setting) }
    DeleteServiceRecordData();

    { Step 7: Delete app files (respects RemoveConfigFiles setting) }
    { Deletes: *.json, *.log, *.exe, *.txt, *.html, *.ttf, _internal\, locales\ }
    { Keeps: *.yaml (unless RemoveConfigFiles = True) }
    DeleteAppFiles();
  end;
end;
